#line 2 "scan.c"

#line 4 "scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE base_yyrestart(base_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int base_yyleng;

extern FILE *base_yyin, *base_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up base_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up base_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via base_yyrestart()), so that the user can continue scanning by
	 * just pointing base_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when base_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int base_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow base_yywrap()'s to do buffer switches
 * instead of setting up a fresh base_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void base_yyrestart (FILE *input_file  );
void base_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE base_yy_create_buffer (FILE *file,int size  );
void base_yy_delete_buffer (YY_BUFFER_STATE b  );
void base_yy_flush_buffer (YY_BUFFER_STATE b  );
void base_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void base_yypop_buffer_state (void );

static void base_yyensure_buffer_stack (void );
static void base_yy_load_buffer_state (void );
static void base_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER base_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE base_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE base_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE base_yy_scan_bytes (yyconst char *bytes,int len  );

void *base_yyalloc (yy_size_t  );
void *base_yyrealloc (void *,yy_size_t  );
void base_yyfree (void *  );

#define yy_new_buffer base_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        base_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            base_yy_create_buffer(base_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        base_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            base_yy_create_buffer(base_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define base_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *base_yyin = (FILE *) 0, *base_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int base_yylineno;

int base_yylineno = 1;

extern char *base_yytext;
#define yytext_ptr base_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up base_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	base_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[155] =
    {   0,
        0,    0,   12,   12,    0,    0,    0,    0,   11,   11,
        0,    0,    0,    0,    0,    0,   53,   51,    1,    1,
       43,   37,   51,   42,   19,   42,   42,   42,   42,   45,
       42,   50,   50,   50,   50,   50,   12,    9,    5,    5,
        6,    6,   40,   38,   11,   16,   25,   25,   21,   30,
       24,   21,   34,   34,   36,    1,   43,   31,   44,   32,
        1,   46,    2,   46,   45,   48,   41,   50,    8,   20,
       18,   15,   12,    9,    9,   10,    5,    7,    4,    3,
       40,   39,   11,   16,   16,   17,   25,   21,   21,   23,
       22,   26,   27,   26,   24,   34,   33,   35,   32,    1,

        1,    2,   46,   49,   47,    9,   14,   10,    9,    3,
       16,   13,   17,   16,   21,   29,   22,   21,   27,   28,
       35,    9,    9,    9,    9,   16,   16,   16,   16,   21,
       21,   21,   21,   27,   28,    9,    9,    9,    9,    9,
       16,   16,   16,   16,   16,   21,   21,   21,   21,   21,
        9,   16,   21,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    5,    7,    8,    5,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   10,    8,
        8,    8,    5,    5,   19,   20,   19,   19,   21,   19,
       22,   22,   22,   22,   22,   22,   22,   23,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   24,   22,   22,
       10,   25,   10,    8,   22,    5,   19,   20,   19,   19,

       21,   19,   22,   22,   22,   22,   22,   22,   22,   23,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   26,
       22,   22,    1,    5,    1,    5,    1,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22
    } ;

static yyconst flex_int32_t yy_meta[27] =
    {   0,
        1,    2,    3,    3,    4,    5,    6,    4,    7,    1,
        8,    4,    9,    1,    8,   10,   10,    1,   11,   11,
       11,   12,   12,   12,   13,   12
    } ;

static yyconst flex_int16_t yy_base[190] =
    {   0,
        0,    0,  162,  161,   22,   33,  163,  162,  154,  153,
       33,   40,  152,  151,   25,   44,  159,  867,   50,   53,
        0,  867,   43,    0,  867,  867,  145,   23,  146,   52,
      138,    0,  142,  141,  138,  137,    0,   72,    0,    0,
       52,  128,    0,  132,    0,   84,    0,    0,   96,   45,
        0,    0,    0,    0,  122,   75,    0,  867,   64,  112,
      105,   73,    0,   75,    0,  109,  867,    0,  867,  867,
      867,  867,    0,    0,   93,  101,    0,   92,  867,    0,
        0,  867,    0,    0,   95,   99,    0,   92,  102,  867,
       82,  867,   77,    0,    0,    0,  867,   77,   65,    0,

      122,    0,  107,   66,  115,  127,  867,   57,  139,    0,
      135,  867,   51,  151,  136,  867,   49,  163,   15,    0,
       22,  175,  187,  199,  211,  223,  235,  247,  259,  271,
      283,  295,  307,  867,  867,  319,  331,    0,  343,  355,
      367,  379,    0,  391,  403,  415,  427,    0,  439,  451,
      463,  475,  487,  867,  500,  513,  526,  539,  552,  565,
      578,  588,  592,  599,  611,  624,  637,  650,  663,  675,
      688,  701,  709,  716,  728,  738,  746,  752,  760,  768,
      768,  774,  786,  799,  812,  816,  827,  840,  853
    } ;

static yyconst flex_int16_t yy_def[190] =
    {   0,
      154,    1,  155,  155,  156,  156,  157,  157,  158,  158,
      159,  159,  160,  160,  161,  161,  154,  154,  154,  154,
      162,  154,  163,  162,  154,  154,  162,  154,  162,  154,
      154,  164,  164,  164,  164,  164,  165,  154,  166,  166,
      154,  154,  167,  154,  168,  154,  169,  169,  154,  170,
      171,   49,  172,  172,  173,  154,  162,  154,  154,  174,
      175,  154,  176,  154,   30,  154,  154,  164,  154,  154,
      154,  154,  165,   38,  177,  154,  166,  154,  154,  178,
      167,  154,  168,   46,  179,  154,  169,   49,  180,  154,
      154,  154,  154,  181,  171,  172,  154,  182,  174,  175,

      175,  176,  154,  154,  154,  177,  154,  154,  183,  178,
      179,  154,  154,  184,  180,  154,  154,  185,  154,  186,
      182,  187,  183,  183,  183,  188,  184,  184,  184,  189,
      185,  185,  185,  154,  154,  187,  187,  106,  187,  183,
      188,  188,  111,  188,  184,  189,  189,  115,  189,  185,
      187,  188,  189,    0,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154
    } ;

static yyconst flex_int16_t yy_nxt[894] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       24,   24,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   32,   35,   36,   18,   36,   40,   54,   97,   40,
      134,   55,   41,   40,   40,   48,   42,   40,   62,   62,
       40,   49,   48,   41,   40,   40,   54,   42,   49,   58,
       55,   56,   56,   56,   56,   56,   56,   50,   59,   59,
       93,  130,   78,  126,   50,   64,   79,   65,   65,  122,
       94,   58,   66,   74,   75,   75,   56,   56,   56,   59,
       59,  105,  105,   97,   76,   84,   85,   85,   62,   62,
      103,  103,  119,   66,  118,   66,   86,   88,   89,   89,

      154,  107,   78,  112,   90,  108,   79,  113,   91,  101,
      116,  114,  101,  109,  117,  101,  101,  101,   58,  101,
      104,  104,  103,  103,  105,  105,  101,   66,   97,  101,
      105,  105,  101,  101,  101,  107,  101,   82,   80,  108,
      124,   75,   75,  112,  116,   72,   71,  113,  117,   70,
       69,  125,  128,   85,   85,   67,   63,   61,  154,   52,
       52,   46,   46,  129,  132,   89,   89,   44,   44,   38,
       38,  154,  154,  154,  154,  133,  137,  138,  138,  154,
      154,  154,  154,  154,  154,  154,  154,  139,  124,   75,
       75,  154,  154,  154,  154,  154,  154,  154,  154,  125,

      124,   75,   75,  154,  154,  154,  154,  154,  154,  154,
      154,  125,  124,   75,   75,  154,  154,  154,  154,  154,
      154,  154,  154,  140,  142,  143,  143,  154,  154,  154,
      154,  154,  154,  154,  154,  144,  128,   85,   85,  154,
      154,  154,  154,  154,  154,  154,  154,  129,  128,   85,
       85,  154,  154,  154,  154,  154,  154,  154,  154,  129,
      128,   85,   85,  154,  154,  154,  154,  154,  154,  154,
      154,  145,  147,  148,  148,  154,  154,  154,  154,  154,
      154,  154,  154,  149,  132,   89,   89,  154,  154,  154,
      154,  154,  154,  154,  154,  133,  132,   89,   89,  154,

      154,  154,  154,  154,  154,  154,  154,  133,  132,   89,
       89,  154,  154,  154,  154,  154,  154,  154,  154,  150,
      137,  138,  138,  154,  154,  154,  154,  154,  154,  154,
      154,  139,  137,  138,  138,  154,  154,  154,  154,  154,
      154,  154,  154,  139,  137,  138,  138,  154,  154,  154,
      154,  154,  154,  154,  154,  151,  124,   75,   75,  154,
      154,  154,  154,  154,  154,  154,  154,  140,  142,  143,
      143,  154,  154,  154,  154,  154,  154,  154,  154,  144,
      142,  143,  143,  154,  154,  154,  154,  154,  154,  154,
      154,  144,  142,  143,  143,  154,  154,  154,  154,  154,

      154,  154,  154,  152,  128,   85,   85,  154,  154,  154,
      154,  154,  154,  154,  154,  145,  147,  148,  148,  154,
      154,  154,  154,  154,  154,  154,  154,  149,  147,  148,
      148,  154,  154,  154,  154,  154,  154,  154,  154,  149,
      147,  148,  148,  154,  154,  154,  154,  154,  154,  154,
      154,  153,  132,   89,   89,  154,  154,  154,  154,  154,
      154,  154,  154,  150,  137,  138,  138,  154,  154,  154,
      154,  154,  154,  154,  154,  151,  142,  143,  143,  154,
      154,  154,  154,  154,  154,  154,  154,  152,  147,  148,
      148,  154,  154,  154,  154,  154,  154,  154,  154,  153,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   57,  154,  154,  154,   57,   57,   60,  154,  154,

      154,   60,   60,   60,   68,  154,  154,  154,   68,   68,
       68,   73,   73,   73,   73,   73,   73,  154,   73,   73,
       73,   73,   73,   73,   77,   77,   77,   77,   77,   77,
       77,  154,   77,   77,   77,   77,   77,   81,   81,   81,
       81,  154,   81,   81,   81,   81,   81,   81,   81,   81,
       83,   83,   83,   83,   83,   83,  154,   83,   83,   83,
       83,   83,   83,   87,   87,   87,   87,   87,   87,  154,
       87,   87,   87,   87,   87,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   95,   95,
       95,   95,   95,   95,  154,   95,   95,   95,   95,   95,

       95,   96,   96,   96,   96,   96,  154,   96,   96,   96,
       96,   96,   96,   96,   98,  154,  154,  154,  154,   98,
       98,   99,  154,  154,  154,   99,   99,   99,  100,  100,
      154,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  102,  154,  154,  154,  102,  102,  106,  106,  154,
      154,  154,  106,  154,  106,  110,  154,  154,  154,  110,
      110,  111,  111,  154,  154,  154,  111,  154,  111,  115,
      115,  154,  154,  154,  115,  154,  115,  120,  120,  121,
      154,  154,  154,  121,  121,  121,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  127,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  135,  135,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,   17,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154

    } ;

static yyconst flex_int16_t yy_chk[894] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,   15,  121,    5,
      119,   15,    5,    5,    5,   11,    5,    6,   28,   28,
        6,   11,   12,    6,    6,    6,   16,    6,   12,   23,
       16,   19,   19,   19,   20,   20,   20,   11,   23,   23,
       50,  117,   41,  113,   12,   30,   41,   30,   30,  108,
       50,   99,   30,   38,   38,   38,   56,   56,   56,   59,
       59,  104,  104,   98,   38,   46,   46,   46,   62,   62,
       64,   64,   93,   62,   91,   64,   46,   49,   49,   49,

       88,   75,   78,   85,   49,   75,   78,   85,   49,   61,
       89,   86,   61,   76,   89,   61,   61,   61,   60,   61,
       66,   66,  103,  103,   66,   66,  101,  103,   55,  101,
      105,  105,  101,  101,  101,  106,  101,   44,   42,  106,
      109,  109,  109,  111,  115,   36,   35,  111,  115,   34,
       33,  109,  114,  114,  114,   31,   29,   27,   17,   14,
       13,   10,    9,  114,  118,  118,  118,    8,    7,    4,
        3,    0,    0,    0,    0,  118,  122,  122,  122,    0,
        0,    0,    0,    0,    0,    0,    0,  122,  123,  123,
      123,    0,    0,    0,    0,    0,    0,    0,    0,  123,

      124,  124,  124,    0,    0,    0,    0,    0,    0,    0,
        0,  124,  125,  125,  125,    0,    0,    0,    0,    0,
        0,    0,    0,  125,  126,  126,  126,    0,    0,    0,
        0,    0,    0,    0,    0,  126,  127,  127,  127,    0,
        0,    0,    0,    0,    0,    0,    0,  127,  128,  128,
      128,    0,    0,    0,    0,    0,    0,    0,    0,  128,
      129,  129,  129,    0,    0,    0,    0,    0,    0,    0,
        0,  129,  130,  130,  130,    0,    0,    0,    0,    0,
        0,    0,    0,  130,  131,  131,  131,    0,    0,    0,
        0,    0,    0,    0,    0,  131,  132,  132,  132,    0,

        0,    0,    0,    0,    0,    0,    0,  132,  133,  133,
      133,    0,    0,    0,    0,    0,    0,    0,    0,  133,
      136,  136,  136,    0,    0,    0,    0,    0,    0,    0,
        0,  136,  137,  137,  137,    0,    0,    0,    0,    0,
        0,    0,    0,  137,  139,  139,  139,    0,    0,    0,
        0,    0,    0,    0,    0,  139,  140,  140,  140,    0,
        0,    0,    0,    0,    0,    0,    0,  140,  141,  141,
      141,    0,    0,    0,    0,    0,    0,    0,    0,  141,
      142,  142,  142,    0,    0,    0,    0,    0,    0,    0,
        0,  142,  144,  144,  144,    0,    0,    0,    0,    0,

        0,    0,    0,  144,  145,  145,  145,    0,    0,    0,
        0,    0,    0,    0,    0,  145,  146,  146,  146,    0,
        0,    0,    0,    0,    0,    0,    0,  146,  147,  147,
      147,    0,    0,    0,    0,    0,    0,    0,    0,  147,
      149,  149,  149,    0,    0,    0,    0,    0,    0,    0,
        0,  149,  150,  150,  150,    0,    0,    0,    0,    0,
        0,    0,    0,  150,  151,  151,  151,    0,    0,    0,
        0,    0,    0,    0,    0,  151,  152,  152,  152,    0,
        0,    0,    0,    0,    0,    0,    0,  152,  153,  153,
      153,    0,    0,    0,    0,    0,    0,    0,    0,  153,

      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  162,    0,    0,    0,  162,  162,  163,    0,    0,

        0,  163,  163,  163,  164,    0,    0,    0,  164,  164,
      164,  165,  165,  165,  165,  165,  165,    0,  165,  165,
      165,  165,  165,  165,  166,  166,  166,  166,  166,  166,
      166,    0,  166,  166,  166,  166,  166,  167,  167,  167,
      167,    0,  167,  167,  167,  167,  167,  167,  167,  167,
      168,  168,  168,  168,  168,  168,    0,  168,  168,  168,
      168,  168,  168,  169,  169,  169,  169,  169,  169,    0,
      169,  169,  169,  169,  169,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  171,  171,
      171,  171,  171,  171,    0,  171,  171,  171,  171,  171,

      171,  172,  172,  172,  172,  172,    0,  172,  172,  172,
      172,  172,  172,  172,  173,    0,    0,    0,    0,  173,
      173,  174,    0,    0,    0,  174,  174,  174,  175,  175,
        0,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  176,    0,    0,    0,  176,  176,  177,  177,    0,
        0,    0,  177,    0,  177,  178,    0,    0,    0,  178,
      178,  179,  179,    0,    0,    0,  179,    0,  179,  180,
      180,    0,    0,    0,  180,    0,  180,  181,  181,  182,
        0,    0,    0,  182,  182,  182,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  184,

      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  186,  186,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int base_yy_flex_debug;
int base_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *base_yytext;
#line 1 "scan.l"
#line 2 "scan.l"
/*-------------------------------------------------------------------------
 *
 * scan.l
 *	  lexical scanner for PostgreSQL
 *
 * NOTE NOTE NOTE:
 *
 * The rules in this file must be kept in sync with psql's lexer!!!
 *
 * The rules are designed so that the scanner never has to backtrack,
 * in the sense that there is always a rule that can match the input
 * consumed so far (the rule action may internally throw back some input
 * with yyless(), however).  As explained in the flex manual, this makes
 * for a useful speed increase --- about a third faster than a plain -CF
 * lexer, in simple testing.  The extra complexity is mostly in the rules
 * for handling float numbers and continued string literals.  If you change
 * the lexical rules, verify that you haven't broken the no-backtrack
 * property by running flex with the "-b" option and checking that the
 * resulting "lex.backup" file says that no backing up is needed.
 *
 *
 * Portions Copyright (c) 2003-2008, PgPool Global Development Group
 * Portions Copyright (c) 1996-2007, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  $PostgreSQL: pgsql/src/backend/parser/scan.l,v 1.141 2007/09/12 20:49:27 adunstan Exp $
 *
 *-------------------------------------------------------------------------
 */
#include "pool_parser.h"

#include <ctype.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <setjmp.h>

#ifndef ereport
#define ereport(a,b) yyerror("")
#endif
#define IS_HIGHBIT_SET(c) 0

#include "gramparse.h"
#include "keywords.h"
/* Not needed now that this file is compiled as part of gram.y */
/* #include "parser/parse.h" */
#include "gram.h"
#include "scansup.h"

#include "pool_memory.h"


/* Avoid exit() on fatal scanner errors (a bit ugly -- see yy_fatal_error) */
/*
#undef fprintf
#define fprintf(file, fmt, msg)  ereport(ERROR, (errmsg_internal("%s", msg)))
*/

static int		xcdepth = 0;	/* depth of nesting in slash-star comments */
static char    *dolqstart;      /* current $foo$ quote start string */

/*
 * GUC variables.  This is a DIRECT violation of the warning given at the
 * head of gram.y, ie flex/bison code must not depend on any GUC variables;
 * as such, changing their values can induce very unintuitive behavior.
 * But we shall have to live with it as a short-term thing until the switch
 * to SQL-standard string syntax is complete.
 */
typedef enum
{
        BACKSLASH_QUOTE_OFF,
        BACKSLASH_QUOTE_ON,
        BACKSLASH_QUOTE_SAFE_ENCODING
} BackslashQuoteType;

BackslashQuoteType backslash_quote = BACKSLASH_QUOTE_SAFE_ENCODING;
int			escape_string_warning = true;
int			standard_conforming_strings = false;

static bool		warn_on_first_escape;
static bool     saw_high_bit = false;

/*
 * literalbuf is used to accumulate literal values when multiple rules
 * are needed to parse a single literal.  Call startlit to reset buffer
 * to empty, addlit to add text.  Note that the buffer is palloc'd and
 * starts life afresh on every parse cycle.
 */
static char	   *literalbuf;		/* expandable buffer */
static int		literallen;		/* actual current length */
static int		literalalloc;	/* current allocated buffer size */

#define startlit()  (literalbuf[0] = '\0', literallen = 0)
static void addlit(char *ytext, int yleng);
static void addlitchar(unsigned char ychar);
static char *litbufdup(void);

#if 0
static int	lexer_errposition(void);
#endif
static void check_escape_warning(void);
static void check_string_escape_warning(unsigned char ychar);

extern char *base_yytext;

/*
 * Each call to base_yylex must set yylloc to the location of the found token
 * (expressed as a byte offset from the start of the input text).
 * When we parse a token that requires multiple lexer rules to process,
 * this should be done in the first such rule, else yylloc will point
 * into the middle of the token.
 */
#define SET_YYLLOC()  (yylloc = base_yytext - scanbuf)

/* Handles to the buffer that the lexer uses internally */
static YY_BUFFER_STATE scanbufhandle;
static char *scanbuf;

static unsigned char unescape_single_char(unsigned char c);
void yyerror(const char *s);

/*
 * OK, here is a short description of lex/flex rules behavior.
 * The longest pattern which matches an input string is always chosen.
 * For equal-length patterns, the first occurring in the rules list is chosen.
 * INITIAL is the starting state, to which all non-conditional rules apply.
 * Exclusive states change parsing rules while the state is active.  When in
 * an exclusive state, only those rules defined for that state apply.
 *
 * We use exclusive states for quoted strings, extended comments,
 * and to eliminate parsing troubles for numeric strings.
 * Exclusive states:
 *  <xb> bit string literal
 *  <xc> extended C-style comments
 *  <xd> delimited identifiers (double-quoted identifiers)
 *  <xh> hexadecimal numeric string
 *  <xq> standard quoted strings
 *  <xe> extended quoted strings (support backslash escape sequences)
 *  <xdolq> $foo$ quoted strings
 */







/*
 * In order to make the world safe for Windows and Mac clients as well as
 * Unix ones, we accept either \n or \r as a newline.  A DOS-style \r\n
 * sequence will be seen as two successive newlines, but that doesn't cause
 * any problems.  Comments that start with -- and extend to the next
 * newline are treated as equivalent to a single whitespace character.
 *
 * NOTE a fine point: if there is no newline following --, we will absorb
 * everything to the end of the input as a comment.  This is correct.  Older
 * versions of Postgres failed to recognize -- as a comment if the input
 * did not end with a newline.
 *
 * XXX perhaps \f (formfeed) should be treated as a newline as well?
 *
 * XXX if you change the set of whitespace characters, fix scanner_isspace()
 * to agree, and see also the plpgsql lexer.
 */
/*
 * SQL requires at least one newline in the whitespace separating
 * string literals that are to be concatenated.  Silly, but who are we
 * to argue?  Note that {whitespace_with_newline} should not have * after
 * it, whereas {whitespace} should generally have a * after it...
 */
/*
 * To ensure that {quotecontinue} can be scanned without having to back up
 * if the full pattern isn't matched, we include trailing whitespace in
 * {quotestop}.  This matches all cases where {quotecontinue} fails to match,
 * except for {quote} followed by whitespace and just one "-" (not two,
 * which would start a {comment}).  To cover that we have {quotefail}.
 * The actions for {quotestop} and {quotefail} must throw back characters
 * beyond the quote proper.
 */
/* Bit string
 * It is tempting to scan the string for only those characters
 * which are allowed. However, this leads to silently swallowed
 * characters if illegal characters are included in the string.
 * For example, if xbinside is [01] then B'ABCD' is interpreted
 * as a zero-length string, and the ABCD' is lost!
 * Better to pass the string forward and let the input routines
 * validate the contents.
 */
/* Hexadecimal number */
/* National character */
/* Quoted string that allows backslash escapes */
/* Extended quote
 * xqdouble implements embedded quote, ''''
 */
/* $foo$ style quotes ("dollar quoting")
 * The quoted string starts with $foo$ where "foo" is an optional string
 * in the form of an identifier, except that it may not contain "$", 
 * and extends to the first occurrence of an identical string.  
 * There is *no* processing of the quoted text.
 *
 * {dolqfailed} is an error rule to avoid scanner backup when {dolqdelim}
 * fails to match its trailing "$".
 */
/* Double quote
 * Allows embedded spaces and other special characters into identifiers.
 */
/* C-style comments
 *
 * The "extended comment" syntax closely resembles allowable operator syntax.
 * The tricky part here is to get lex to recognize a string starting with
 * slash-star as a comment, when interpreting it as an operator would produce
 * a longer match --- remember lex will prefer a longer match!  Also, if we
 * have something like plus-slash-star, lex will think this is a 3-character
 * operator whereas we want to see it as a + operator and a comment start.
 * The solution is two-fold:
 * 1. append {op_chars}* to xcstart so that it matches as much text as
 *    {operator} would. Then the tie-breaker (first matching rule of same
 *    length) ensures xcstart wins.  We put back the extra stuff with yyless()
 *    in case it contains a star-slash that should terminate the comment.
 * 2. In the operator rule, check for slash-star within the operator, and
 *    if found throw it back with yyless().  This handles the plus-slash-star
 *    problem.
 * Dash-dash comments have similar interactions with the operator rule.
 */
/*
 * "self" is the set of chars that should be returned as single-character
 * tokens.  "op_chars" is the set of chars that can make up "Op" tokens,
 * which can be one or more characters long (but if a single-char token
 * appears in the "self" set, it is not to be returned as an Op).  Note
 * that the sets overlap, but each has some chars that are not in the other.
 *
 * If you change either set, adjust the character lists appearing in the
 * rule for "operator"!
 */
/* we no longer allow unary minus in numbers. 
 * instead we pass it separately to parser. there it gets
 * coerced via doNegate() -- Leon aug 20 1999
 *
 * {realfail1} and {realfail2} are added to prevent the need for scanner
 * backup when the {real} rule fails to match completely.
 */
/*
 * Dollar quoted strings are totally opaque, and no escaping is done on them.
 * Other quoted strings must allow some special characters such as single-quote
 *  and newline.
 * Embedded single-quotes are implemented both in the SQL standard
 *  style of two adjacent single quotes "''" and in the Postgres/Java style
 *  of escaped-quote "\'".
 * Other embedded escaped characters are matched explicitly and the leading
 *  backslash is dropped from the string.
 * Note that xcstart must appear before operator, as explained above!
 *  Also whitespace (comment) must appear before operator.
 */
#line 964 "scan.c"

#define INITIAL 0
#define xb 1
#define xc 2
#define xd 3
#define xh 4
#define xe 5
#define xq 6
#define xdolq 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int base_yywrap (void );
#else
extern int base_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( base_yytext, base_yyleng, 1, base_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( base_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( base_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, base_yyin))==0 && ferror(base_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(base_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int base_yylex (void);

#define YY_DECL int base_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after base_yytext and base_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 345 "scan.l"


#line 1125 "scan.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! base_yyin )
			base_yyin = stdin;

		if ( ! base_yyout )
			base_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			base_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				base_yy_create_buffer(base_yyin,YY_BUF_SIZE );
		}

		base_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of base_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 155 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 154 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 347 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 351 "scan.l"
{
					/* Set location in case of syntax error in comment */
					SET_YYLLOC();
					xcdepth = 0;
					BEGIN(xc);
					/* Put back any characters past slash-star; see above */
					yyless(2);
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 360 "scan.l"
{
					xcdepth++;
					/* Put back any characters past slash-star; see above */
					yyless(2);
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 366 "scan.l"
{
					if (xcdepth <= 0)
						BEGIN(INITIAL);
					else
						xcdepth--;
				}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 373 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 377 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 381 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case YY_STATE_EOF(xc):
#line 385 "scan.l"
{ yyerror("unterminated /* comment"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 387 "scan.l"
{
					/* Binary bit type.
					 * At some point we should simply pass the string
					 * forward to the parser and label it there.
					 * In the meantime, place a leading "b" on the string
					 * to mark it for the input routine as a binary string.
					 */
					SET_YYLLOC();
					BEGIN(xb);
					startlit();
					addlitchar('b');
				}
	YY_BREAK
case 9:
/* rule 9 can match eol */
#line 400 "scan.l"
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 400 "scan.l"
{
					yyless(1);
					BEGIN(INITIAL);
					yylval.str = litbufdup();
					return BCONST;
				}
	YY_BREAK
case 11:
/* rule 11 can match eol */
#line 407 "scan.l"
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 407 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case 13:
/* rule 13 can match eol */
#line 411 "scan.l"
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 411 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case YY_STATE_EOF(xb):
#line 414 "scan.l"
{ yyerror("unterminated bit string literal"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 416 "scan.l"
{
					/* Hexadecimal bit type.
					 * At some point we should simply pass the string
					 * forward to the parser and label it there.
					 * In the meantime, place a leading "x" on the string
					 * to mark it for the input routine as a hex string.
					 */
					SET_YYLLOC();
					BEGIN(xh);
					startlit();
					addlitchar('x');
				}
	YY_BREAK
case 16:
/* rule 16 can match eol */
#line 429 "scan.l"
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 429 "scan.l"
{
					yyless(1);
					BEGIN(INITIAL);
					yylval.str = litbufdup();
					return XCONST;
				}
	YY_BREAK
case YY_STATE_EOF(xh):
#line 435 "scan.l"
{ yyerror("unterminated hexadecimal string literal"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 437 "scan.l"
{
					/* National character.
					 * We will pass this along as a normal character string,
					 * but preceded with an internally-generated "NCHAR".
					 */
					const ScanKeyword *keyword;

					SET_YYLLOC();
					yyless(1);				/* eat only 'n' this time */
					/* nchar had better be a keyword! */
					keyword = ScanKeywordLookup("nchar");
					yylval.keyword = keyword->name;
					return keyword->value;
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 452 "scan.l"
{
					warn_on_first_escape = true;
					saw_high_bit = false;
					SET_YYLLOC();
					if (standard_conforming_strings)
						BEGIN(xq);
					else
						BEGIN(xe);
					startlit();
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 462 "scan.l"
{
					warn_on_first_escape = false;
					saw_high_bit = false;
					SET_YYLLOC();
					BEGIN(xe);
					startlit();
				}
	YY_BREAK
case 21:
/* rule 21 can match eol */
#line 470 "scan.l"
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 470 "scan.l"
{
					yyless(1);
					BEGIN(INITIAL);
					/* check that the data remains valid if it might have been
					 * made invalid by unescaping any chars.
					 */
					if (saw_high_bit);
/*						pg_verifymbstr(literalbuf, literallen, false);*/
					yylval.str = litbufdup();
					return SCONST;
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 481 "scan.l"
{
					addlitchar('\'');
				}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 484 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 487 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 490 "scan.l"
{
					if (base_yytext[1] == '\'')
					{
#if 0
						if (backslash_quote == BACKSLASH_QUOTE_OFF ||
							(backslash_quote == BACKSLASH_QUOTE_SAFE_ENCODING &&
							 PG_ENCODING_IS_CLIENT_ONLY(pg_get_client_encoding())))
							ereport(ERROR,
									(errcode(ERRCODE_NONSTANDARD_USE_OF_ESCAPE_CHARACTER),
									 errmsg("unsafe use of \\' in a string literal"),
									 errhint("Use '' to write quotes in strings. \\' is insecure in client-only encodings."),
									 lexer_errposition()));
#endif
					}
					check_string_escape_warning(base_yytext[1]);
					addlitchar(unescape_single_char(base_yytext[1]));
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 507 "scan.l"
{
					unsigned char c = strtoul(base_yytext+1, NULL, 8);

					check_escape_warning();
					addlitchar(c);
					if (IS_HIGHBIT_SET(c))
						saw_high_bit = true;
				}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 515 "scan.l"
{
					unsigned char c = strtoul(base_yytext+2, NULL, 16);

					check_escape_warning();
					addlitchar(c);
					if (IS_HIGHBIT_SET(c))
						saw_high_bit = true;
				}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 523 "scan.l"
{
					/* ignore */
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 526 "scan.l"
{
					/* This is only needed for \ just before EOF */
					addlitchar(base_yytext[0]);
				}
	YY_BREAK
case YY_STATE_EOF(xq):
case YY_STATE_EOF(xe):
#line 530 "scan.l"
{ yyerror("unterminated quoted string"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 532 "scan.l"
{
					SET_YYLLOC();
					dolqstart = pstrdup(base_yytext);
					BEGIN(xdolq);
					startlit();
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 538 "scan.l"
{
					/* throw back all but the initial "$" */
					yyless(1);
					/* and treat it as {other} */
					return base_yytext[0];
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 544 "scan.l"
{
					if (strcmp(base_yytext, dolqstart) == 0)
					{
						pfree(dolqstart);
						BEGIN(INITIAL);
						yylval.str = litbufdup();
						return SCONST;
					}
					else
					{
						/*
						 * When we fail to match $...$ to dolqstart, transfer
						 * the $... part to the output, but put back the final
						 * $ for rescanning.  Consider $delim$...$junk$delim$
						 */
						addlit(base_yytext, base_yyleng-1);
						yyless(base_yyleng-1);
					}
				}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 563 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 566 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 569 "scan.l"
{
					/* This is only needed for $ inside the quoted text */
					addlitchar(base_yytext[0]);
				}
	YY_BREAK
case YY_STATE_EOF(xdolq):
#line 573 "scan.l"
{ yyerror("unterminated dollar-quoted string"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 575 "scan.l"
{
					SET_YYLLOC();
					BEGIN(xd);
					startlit();
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 580 "scan.l"
{
					char		   *ident;

					BEGIN(INITIAL);
					if (literallen == 0)
						yyerror("zero-length delimited identifier");
					ident = litbufdup();
					if (literallen >= NAMEDATALEN)
						truncate_identifier(ident, literallen, true);
					yylval.str = ident;
					return IDENT;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 592 "scan.l"
{
					addlitchar('"');
				}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 595 "scan.l"
{
					addlit(base_yytext, base_yyleng);
				}
	YY_BREAK
case YY_STATE_EOF(xd):
#line 598 "scan.l"
{ yyerror("unterminated quoted identifier"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 600 "scan.l"
{
					SET_YYLLOC();
					return TYPECAST;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 605 "scan.l"
{
					SET_YYLLOC();
					return base_yytext[0];
				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 610 "scan.l"
{
					/*
					 * Check for embedded slash-star or dash-dash; those
					 * are comment starts, so operator must stop there.
					 * Note that slash-star or dash-dash at the first
					 * character will match a prior rule, not this one.
					 */
					int		nchars = base_yyleng;
					char   *slashstar = strstr(base_yytext, "/*");
					char   *dashdash = strstr(base_yytext, "--");

					if (slashstar && dashdash)
					{
						/* if both appear, take the first one */
						if (slashstar > dashdash)
							slashstar = dashdash;
					}
					else if (!slashstar)
						slashstar = dashdash;
					if (slashstar)
						nchars = slashstar - base_yytext;

					/*
					 * For SQL compatibility, '+' and '-' cannot be the
					 * last char of a multi-char operator unless the operator
					 * contains chars that are not in SQL operators.
					 * The idea is to lex '=-' as two operators, but not
					 * to forbid operator names like '?-' that could not be
					 * sequences of SQL operators.
					 */
					while (nchars > 1 &&
						   (base_yytext[nchars-1] == '+' ||
							base_yytext[nchars-1] == '-'))
					{
						int		ic;

						for (ic = nchars-2; ic >= 0; ic--)
						{
							if (strchr("~!@#^&|`?%", base_yytext[ic]))
								break;
						}
						if (ic >= 0)
							break; /* found a char that makes it OK */
						nchars--; /* else remove the +/-, and check again */
					}

					SET_YYLLOC();

					if (nchars < base_yyleng)
					{
						/* Strip the unwanted chars from the token */
						yyless(nchars);
						/*
						 * If what we have left is only one char, and it's
						 * one of the characters matching "self", then
						 * return it as a character token the same way
						 * that the "self" rule would have.
						 */
						if (nchars == 1 &&
							strchr(",()[].;:+-*/%^<>=", base_yytext[0]))
							return base_yytext[0];
					}

					/*
					 * Complain if operator is too long.  Unlike the case
					 * for identifiers, we make this an error not a notice-
					 * and-truncate, because the odds are we are looking at
					 * a syntactic mistake anyway.
					 */
					if (nchars >= NAMEDATALEN)
						yyerror("operator too long");

					/* Convert "!=" operator to "<>" for compatibility */
					if (strcmp(base_yytext, "!=") == 0)
						yylval.str = pstrdup("<>");
					else
						yylval.str = pstrdup(base_yytext);
					return Op;
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 690 "scan.l"
{
					SET_YYLLOC();
					yylval.ival = atol(base_yytext + 1);
					return PARAM;
				}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 696 "scan.l"
{
					long val;
					char* endptr;

					SET_YYLLOC();
					errno = 0;
					val = strtol(base_yytext, &endptr, 10);
					if (*endptr != '\0' || errno == ERANGE
#ifdef HAVE_LONG_INT_64
						/* if long > 32 bits, check for overflow of int4 */
						|| val != (long) ((int32) val)
#endif
						)
					{
						/* integer too large, treat it as a float */
						yylval.str = pstrdup(base_yytext);
						return FCONST;
					}
					yylval.ival = val;
					return ICONST;
				}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 717 "scan.l"
{
					SET_YYLLOC();
					yylval.str = pstrdup(base_yytext);
					return FCONST;
				}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 722 "scan.l"
{
					SET_YYLLOC();
					yylval.str = pstrdup(base_yytext);
					return FCONST;
				}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 727 "scan.l"
{
					/*
					 * throw back the [Ee], and treat as {decimal}.  Note
					 * that it is possible the input is actually {integer},
					 * but since this case will almost certainly lead to a
					 * syntax error anyway, we don't bother to distinguish.
					 */
					yyless(base_yyleng-1);
					SET_YYLLOC();
					yylval.str = pstrdup(base_yytext);
					return FCONST;
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 739 "scan.l"
{
					/* throw back the [Ee][+-], and proceed as above */
					yyless(base_yyleng-2);
					SET_YYLLOC();
					yylval.str = pstrdup(base_yytext);
					return FCONST;
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 748 "scan.l"
{
					const ScanKeyword *keyword;
					char		   *ident;

					SET_YYLLOC();

					/* Is it a keyword? */
					keyword = ScanKeywordLookup(base_yytext);
					if (keyword != NULL)
					{
						yylval.keyword = keyword->name;
						return keyword->value;
					}

					/*
					 * No.  Convert the identifier to lower case, and truncate
					 * if necessary.
					 */
					ident = downcase_truncate_identifier(base_yytext, base_yyleng, true);
					yylval.str = ident;
					return IDENT;
				}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 771 "scan.l"
{
					SET_YYLLOC();
					return base_yytext[0];
				}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 776 "scan.l"
{
					SET_YYLLOC();
					yyterminate();
				}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 781 "scan.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1849 "scan.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed base_yyin at a new source and called
			 * base_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = base_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( base_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * base_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of base_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					base_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			base_yyrestart(base_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 155 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 155 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 154);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					base_yyrestart(base_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( base_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve base_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void base_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        base_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            base_yy_create_buffer(base_yyin,YY_BUF_SIZE );
	}

	base_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	base_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void base_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		base_yypop_buffer_state();
	 *		base_yypush_buffer_state(new_buffer);
     */
	base_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	base_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (base_yywrap()) processing, but the only time this flag
	 * is looked at is after base_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void base_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	base_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE base_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) base_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in base_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) base_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in base_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	base_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with base_yy_create_buffer()
 * 
 */
    void base_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		base_yyfree((void *) b->yy_ch_buf  );

	base_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a base_yyrestart() or at EOF.
 */
    static void base_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	base_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then base_yy_init_buffer was _probably_
     * called from base_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void base_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		base_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void base_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	base_yyensure_buffer_stack();

	/* This block is copied from base_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from base_yy_switch_to_buffer. */
	base_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void base_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	base_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		base_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void base_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)base_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)base_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE base_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) base_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in base_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	base_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to base_yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       base_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE base_yy_scan_string (yyconst char * yystr )
{
    
	return base_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to base_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE base_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) base_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in base_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = base_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in base_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up base_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		base_yytext[base_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = base_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		base_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int base_yyget_lineno  (void)
{
        
    return base_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *base_yyget_in  (void)
{
        return base_yyin;
}

/** Get the output stream.
 * 
 */
FILE *base_yyget_out  (void)
{
        return base_yyout;
}

/** Get the length of the current token.
 * 
 */
int base_yyget_leng  (void)
{
        return base_yyleng;
}

/** Get the current token.
 * 
 */

char *base_yyget_text  (void)
{
        return base_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void base_yyset_lineno (int  line_number )
{
    
    base_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see base_yy_switch_to_buffer
 */
void base_yyset_in (FILE *  in_str )
{
        base_yyin = in_str ;
}

void base_yyset_out (FILE *  out_str )
{
        base_yyout = out_str ;
}

int base_yyget_debug  (void)
{
        return base_yy_flex_debug;
}

void base_yyset_debug (int  bdebug )
{
        base_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from base_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    base_yyin = stdin;
    base_yyout = stdout;
#else
    base_yyin = (FILE *) 0;
    base_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * base_yylex_init()
     */
    return 0;
}

/* base_yylex_destroy is for both reentrant and non-reentrant scanners. */
int base_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		base_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		base_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	base_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * base_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *base_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *base_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void base_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see base_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 781 "scan.l"



/*
 * lexer_errposition
 *		Report a lexical-analysis-time cursor position, if possible.
 *
 * This is expected to be used within an ereport() call.  The return value
 * is a dummy (always 0, in fact).
 *
 * Note that this can only be used for messages from the lexer itself,
 * since it depends on scanbuf to still be valid.
 */
#if 0
static int
lexer_errposition(void)
{
	int		pos;

	/* Convert byte offset to character number */
	pos = pg_mbstrlen_with_len(scanbuf, yylloc) + 1;
	/* And pass it to the ereport mechanism */
	return errposition(pos);
}
#endif

/*
 * yyerror
 *		Report a lexer or grammar error.
 *
 * The message's cursor position identifies the most recently lexed token.
 * This is OK for syntax error messages from the Bison parser, because Bison
 * parsers report error as soon as the first unparsable token is reached.
 * Beware of using yyerror for other purposes, as the cursor position might
 * be misleading!
 */
void
yyerror(const char *message)
{
	longjmp(jmpbuffer, 1);
}


/*
 * Called before any actual parsing is done
 */
void
scanner_init(const char *str)
{
	int	slen = strlen(str);

	/*
	 * Might be left over after ereport()
	 */
	if (YY_CURRENT_BUFFER)
		base_yy_delete_buffer(YY_CURRENT_BUFFER);

	/*
	 * Make a scan buffer with special termination needed by flex.
	 */
	scanbuf = palloc(slen + 2);
	memcpy(scanbuf, str, slen);
	scanbuf[slen] = scanbuf[slen + 1] = YY_END_OF_BUFFER_CHAR;
	scanbufhandle = base_yy_scan_buffer(scanbuf,slen + 2);

	/* initialize literal buffer to a reasonable but expansible size */
	literalalloc = 1024;
	literalbuf = (char *) palloc(literalalloc);
	startlit();

	BEGIN(INITIAL);
}


/*
 * Called after parsing is done to clean up after scanner_init()
 */
void
scanner_finish(void)
{
	base_yy_delete_buffer(scanbufhandle);
	pfree(scanbuf);
}


static void
addlit(char *ytext, int yleng)
{
	/* enlarge buffer if needed */
	if ((literallen+yleng) >= literalalloc)
	{
		do {
			literalalloc *= 2;
		} while ((literallen+yleng) >= literalalloc);
		literalbuf = (char *) repalloc(literalbuf, literalalloc);
	}
	/* append new data, add trailing null */
	memcpy(literalbuf+literallen, ytext, yleng);
	literallen += yleng;
	literalbuf[literallen] = '\0';
}


static void
addlitchar(unsigned char ychar)
{
	/* enlarge buffer if needed */
	if ((literallen+1) >= literalalloc)
	{
		literalalloc *= 2;
		literalbuf = (char *) repalloc(literalbuf, literalalloc);
	}
	/* append new data, add trailing null */
	literalbuf[literallen] = ychar;
	literallen += 1;
	literalbuf[literallen] = '\0';
}


/*
 * One might be tempted to write pstrdup(literalbuf) instead of this,
 * but for long literals this is much faster because the length is
 * already known.
 */
static char *
litbufdup(void)
{
	char *new;

	new = palloc(literallen + 1);
	memcpy(new, literalbuf, literallen+1);
	return new;
}


static unsigned char
unescape_single_char(unsigned char c)
{
	/* Normally we wouldn't expect to see \n where n has its high bit set
	 * but we set the flag to check the string if we do get it, so
	 * that this doesn't become a way of getting around the coding validity
	 * checks.
	 */
	if (IS_HIGHBIT_SET(c))
		saw_high_bit = true;

	switch (c)
	{
		case 'b':
			return '\b';
		case 'f':
			return '\f';
		case 'n':
			return '\n';
		case 'r':
			return '\r';
		case 't':
			return '\t';
		default:
			return c;
	}
}

static void
check_string_escape_warning(unsigned char ychar)
{
#if 0
	if (ychar == '\'')
	{
		if (warn_on_first_escape && escape_string_warning)
			ereport(WARNING,
					(errcode(ERRCODE_NONSTANDARD_USE_OF_ESCAPE_CHARACTER),
					 errmsg("nonstandard use of \\' in a string literal"),
					 errhint("Use '' to write quotes in strings, or use the escape string syntax (E'...')."),
					 lexer_errposition()));
		warn_on_first_escape = false;	/* warn only once per string */
	}
	else if (ychar == '\\')
	{
		if (warn_on_first_escape && escape_string_warning)
			ereport(WARNING,
					(errcode(ERRCODE_NONSTANDARD_USE_OF_ESCAPE_CHARACTER),
					 errmsg("nonstandard use of \\\\ in a string literal"),
					 errhint("Use the escape string syntax for backslashes, e.g., E'\\\\'."),
					 lexer_errposition()));
		warn_on_first_escape = false;	/* warn only once per string */
	}
	else
		check_escape_warning();
#endif
}

static void
check_escape_warning(void)
{
#if 0
	if (warn_on_first_escape && escape_string_warning)
		ereport(WARNING,
				(errcode(ERRCODE_NONSTANDARD_USE_OF_ESCAPE_CHARACTER),
				 errmsg("nonstandard use of escape in a string literal"),
				 errhint("Use the escape string syntax for escapes, e.g., E'\\r\\n'."),
				 lexer_errposition()));
	warn_on_first_escape = false;	/* warn only once per string */
#endif
}

/*
 * downcase_truncate_identifier() --- do appropriate downcasing and
 * truncation of an unquoted identifier.  Optionally warn of truncation.
 *
 * Returns a palloc'd string containing the adjusted identifier.
 *
 * Note: in some usages the passed string is not null-terminated.
 *
 * Note: the API of this function is designed to allow for downcasing
 * transformations that increase the string length, but we don't yet
 * support that.  If you want to implement it, you'll need to fix
 * SplitIdentifierString() in utils/adt/varlena.c.
 */
char *
downcase_truncate_identifier(const char *ident, int len, int warn)
{
	char	   *result;
	int			i;

	result = palloc(len + 1);

	/*
	 * SQL99 specifies Unicode-aware case normalization, which we don't yet
	 * have the infrastructure for.  Instead we use tolower() to provide a
	 * locale-aware translation.  However, there are some locales where this
	 * is not right either (eg, Turkish may do strange things with 'i' and
	 * 'I').  Our current compromise is to use tolower() for characters with
	 * the high bit set, and use an ASCII-only downcasing for 7-bit
	 * characters.
	 */
	for (i = 0; i < len; i++)
	{
		unsigned char ch = (unsigned char) ident[i];

		if (ch >= 'A' && ch <= 'Z')
			ch += 'a' - 'A';
		else if (ch >= 0x80 && isupper(ch))
			ch = tolower(ch);
		result[i] = (char) ch;
	}
	result[i] = '\0';

	if (i >= NAMEDATALEN)
		truncate_identifier(result, i, warn);

	return result;
}

/*
 * truncate_identifier() --- truncate an identifier to NAMEDATALEN-1 bytes.
 *
 * The given string is modified in-place, if necessary.  A warning is
 * issued if requested.
 *
 * We require the caller to pass in the string length since this saves a
 * strlen() call in some common usages.
 */
void
truncate_identifier(char *ident, int len, int warn)
{
	if (len >= NAMEDATALEN)
	{
		len = strlen(ident); /*pg_mbcliplen(ident, len, NAMEDATALEN - 1);*/
#if 0
		if (warn)
			ereport(NOTICE,
					(errcode(ERRCODE_NAME_TOO_LONG),
					 errmsg("identifier \"%s\" will be truncated to \"%.*s\"",
							ident, len, ident)));
#endif
		ident[len] = '\0';
	}
}

